In [1]:
import numpy as np

In [3]:
x = np.arange(0, 11)

In [4]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
y = (80 - 3*x) / 7

In [6]:
y

array([11.42857143, 11.        , 10.57142857, 10.14285714,  9.71428571,
        9.28571429,  8.85714286,  8.42857143,  8.        ,  7.57142857,
        7.14285714])

In [7]:
y[y < 10]

array([9.71428571, 9.28571429, 8.85714286, 8.42857143, 8.        ,
       7.57142857, 7.14285714])

In [11]:
z = np.array(list(zip(x, y)))

In [12]:
z

array([[ 0.        , 11.42857143],
       [ 1.        , 11.        ],
       [ 2.        , 10.57142857],
       [ 3.        , 10.14285714],
       [ 4.        ,  9.71428571],
       [ 5.        ,  9.28571429],
       [ 6.        ,  8.85714286],
       [ 7.        ,  8.42857143],
       [ 8.        ,  8.        ],
       [ 9.        ,  7.57142857],
       [10.        ,  7.14285714]])

In [19]:
np.array(list(filter(lambda x: x[1] < 10, z)))

array([[ 4.        ,  9.71428571],
       [ 5.        ,  9.28571429],
       [ 6.        ,  8.85714286],
       [ 7.        ,  8.42857143],
       [ 8.        ,  8.        ],
       [ 9.        ,  7.57142857],
       [10.        ,  7.14285714]])